### ISSUE TITLE
Error on player load

### ISSUE THREAD

**Issue by Zamrod** [CDeenen/SharedVision#14]
When a player loads into my game they immediately get the following error:

```
foundry.js:319 TypeError: Cannot read properties of undefined (reading '_getTriggersFromTokens')
[Detected 1 package: SharedVision]
    at triggerHappy_ControlToken (externalModules.js:95:34)
    at sharedvision.js:19:73
    at Function._call (foundry.js:294:14)
    at Function.callAll (foundry.js:253:12)
    at Token5e.control (foundry.js:21652:11)
    at Canvas._initializeTokenControl (foundry.js:20312:13)
    at Canvas._initialize (foundry.js:20226:10)
    at async Canvas.draw (foundry.js:20078:7)
    at async Scene.view (foundry.js:17803:7)
    at async Game.initializeCanvas (foundry.js:5679:20)
    at async Game.setupGame (foundry.js:5550:5)
    at async Game._initializeGameView (foundry.js:6510:5)
    at async Game.initialize (foundry.js:5433:5)
```

**Comment by CDeenen** [comment]
Thanks for you bug report.
The bug is part of the Trigger Happy compatibility. It looks like something changed in Trigger Happy.
I'll look into it.
