### ISSUE TITLE
[BUG] Incompatibility with "Levels" Module

### ISSUE THREAD

**Issue by cglatot** [CDeenen/SharedVision#22]
**Setup**
 - OS: Docker on Unraid (server) | Windows 10 (client)
 - Browser: Google Chrome 104.0.5112.102 (Official Build) (64-bit)
 - Module version: 1.0.9
 - Foundry version: 9.269
 - Gaming system & version: DnD 5e 1.6.3
 - Any other modules enabled: Yes - but I went through them all and tested, and Levels is the **only** module to create this issue.

**Describe the bug**
When both **Levels** and **Shared Vision** modules are enabled; when a token that has granted shared vision is _moved_ that token (and any tokens that only that token can see) disappear. This happens when all tokens are in the same scene, as well as across different scenes.

**Screenshots**
This is the initial setup from the DM view. The 2 players beneath the under the boulder cannot see the zombie - as expected:
![image](https://user-images.githubusercontent.com/10439257/185811729-c02dfb7e-205c-4708-8bf4-c130ebefc960.png).
Here is the setup from the players view:
![image](https://user-images.githubusercontent.com/10439257/185811795-a799c79c-076e-4396-8bf0-a04661ce0b02.png)
All is fine so far.
When one of the players moves up to the rock, the other player (both players have shared vision) SHOULD see the zombie behind the rock as well as the other player, like in this image:
![image](https://user-images.githubusercontent.com/10439257/185811883-4b50bea0-4d84-4a87-b5bd-6f80d3e6fd0a.png)
However, when the Levels module is enabled, this is what happens:
![image](https://user-images.githubusercontent.com/10439257/185811920-a7f8ef73-255f-4463-85cb-33ff5af2801f.png)
As you can see - both the other player and the token disappear. However, the FoW is still updated. Just not the tokens.

**Console Log**
I get these console errors regardless of whether Levels is enabled or Disabled. There are no other errors in the console.

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'getFlag')
[Detected 1 package: SharedVision]
    at initializeSources (misc.js:51:32)
    at onCanvasReady (sharedvision.js:92:10)
    at sharedvision.js:17:73
    at Hooks._call (foundry.js:294:14)
    at Hooks.call (foundry.js:279:33)
    at Canvas.draw (foundry.js:20143:13)
    at async Scene.view (foundry.js:17859:7)
    at async Game.initializeCanvas (foundry.js:5677:20)
    at async Game.setupGame (foundry.js:5548:5)
    at async Game._initializeGameView (foundry.js:6514:5)
    at async Game.initialize (foundry.js:5431:5)
```

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'getFlag')
[Detected 1 package: SharedVision]
    at initializeSources (misc.js:51:32)
    at sharedvision.js:82:26
    at Hooks._call (foundry.js:294:14)
    at Hooks.callAll (foundry.js:253:12)
    at Game.setupGame (foundry.js:5567:11)
    at async Game._initializeGameView (foundry.js:6514:5)
    at async Game.initialize (foundry.js:5431:5)
```

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'getFlag')
[Detected 1 package: SharedVision]
    at initializeSources (misc.js:51:32)
    at o.<anonymous> (socket.js:10:69)
    at T.emit (index.js:143:20)
    at o.value (socket.js:276:20)
    at o.value (socket.js:263:18)
    at o.value (socket.js:231:22)
    at T.emit (index.js:143:20)
    at s.value (manager.js:200:14)
    at T.emit (index.js:143:20)
    at a.value (index.js:105:51)
    at s.value (manager.js:192:22)
    at T.emit (index.js:143:20)
    at a.value (socket.js:323:26)
    at T.emit (index.js:143:20)
    at o.value (transport.js:99:14)
    at o.value (transport.js:92:14)
    at ws.onmessage (websocket.js:76:40)
```

**Additional context**
This only affects the players, not the DM.
A refresh does not fix this.
This happens even if there are no actual levels configured.
I've tried configuring multiple levels as well, just to see if the problem was that I didn't have any levels defined, and the same behaviour happens.
Just enabling the Levels module without doing anything else causes this problem.
I also couldn't see any settings in the Levels module that would affect this.

**Comment by cglatot** [comment]
I know that you've listed that Levels is not compatible, but wanted to post this issue anyway as I didn't see it elsewhere, and hoping that the behaviour and errors help out.

**Comment by cglatot** [comment]
Nevermind, I somehow didn't see the already opened #11 ...... This will teach me to do things late at night
