### ISSUE TITLE
[BUG] Console errors when loading module

### ISSUE THREAD

**Issue by Weissrolf** [CDeenen/SharedVision#25]
**Setup**
 - OS: Windows
 - Browser: Brave (Chromium)
 - Module version: 1.1.1
 - Foundry version: 10.285
 - Gaming system & version: PF2 4.0.4
 - Any other modules enabled: no

**Console Log**

tokenLayer.js:95 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'id')
[Detected 2 packages: SharedVision, monks-tokenbar]
    at updateToken (tokenLayer.js:95:72)
    at updateAllTokens (tokenLayer.js:120:9)
    at initializeSources (misc.js:81:3)
    at onCanvasReady (sharedvision.js:118:5)
    at Object.fn (sharedvision.js:21:75)
    at #call (foundry.js:688:20)
    at Hooks.call (foundry.js:670:38)
    at Canvas.draw (foundry.js:23578:13)
    at async ScenePF2e.view (foundry.js:20803:7)
    at async ScenePF2e.sceneView (monks-tokenbar.js:128:20)
    at async Game.initializeCanvas (foundry.js:7966:20)
    at async Game.setupGame (foundry.js:7804:5)
    at async Game._initializeGameView (foundry.js:8877:5)
    at async Game.initialize (foundry.js:7687:5)
updateToken @ tokenLayer.js:95
updateAllTokens @ tokenLayer.js:120
initializeSources @ misc.js:81
onCanvasReady @ sharedvision.js:118
(anonymous) @ sharedvision.js:21
#call @ foundry.js:688
call @ foundry.js:670
draw @ foundry.js:23578
await in draw (async)
view @ foundry.js:20803
🎁call_wrapped @ libWrapper-wrapper.js:511
sceneView @ monks-tokenbar.js:128
🎁call_wrapper @ libWrapper-wrapper.js:620
🎁Scene.prototype.view#0 @ libWrapper-wrapper.js:189
initializeCanvas @ foundry.js:7966
await in initializeCanvas (async)
setupGame @ foundry.js:7798
await in setupGame (async)
_initializeGameView @ foundry.js:8877
_initializeView @ foundry.js:8853
initialize @ foundry.js:7687
await in initialize (async)
🎁call_wrapped @ libWrapper-wrapper.js:511
🎁libWrapperInit @ libWrapper-api.js:805
await in 🎁libWrapperInit (async)
🎁Game.prototype.initialize#0 @ libWrapper-wrapper.js:187
window.addEventListener.once @ foundry.js:78804

tokenLayer.js:95 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'id')
[Detected 1 package: SharedVision]
    at updateToken (tokenLayer.js:95:72)
    at updateAllTokens (tokenLayer.js:120:9)
    at initializeSources (misc.js:81:3)
    at onReady (sharedvision.js:86:5)
    at Object.fn (sharedvision.js:18:75)
    at #call (foundry.js:688:20)
    at Hooks.callAll (foundry.js:645:17)
    at Game.setupGame (foundry.js:7826:11)
    at async Game._initializeGameView (foundry.js:8877:5)
    at async Game.initialize (foundry.js:7687:5)

**Comment by Weissrolf** [comment]
This did not happen for quite some time and I forgot about it. Thanks for getting back to me/it, though. I posted that I had no other modules enabled and I would assume that I tested this using Find the Culprit back then. But the error I posted here includes Monk's Tokenbar, so maybe I botched that part back then?!

**Comment by CDeenen** [comment]
Yeah, the mention of Monk's Tokenbar is a bit suspect :p. In any case, if it only happens when loading the module I don't expect that this error should cause any real issues. 
I'll close this for now, if it pops up again feel free to reopen this issue or create a new one.
